#ifndef _LEGENDENGINE_MATH_CONSTANTS_HPP
#define _LEGENDENGINE_MATH_CONSTANTS_HPP

namespace LegendEngine::Math
{
	constexpr const float PI = 3.14159265358979323846f;
}

#endif //_LEGENDENGINE_MATH_CONSTANTS_HPP