name: Build and test (Linux)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          test -f /usr/share/doc/kitware-archive-keyring/copyright ||
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt update
          sudo apt install -y cmake ninja-build libvulkan-dev vulkan-validationlayers vulkan-tools mesa-vulkan-drivers glslc g++-14 ca-certificates gpg wget

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja --target NormalTests -DCMAKE_CXX_COMPILER=g++-14 -DCMAKE_BUILD_TYPE=Release -DLGENG_BUILD_TESTS=ON -DTETHER_HEADLESS=ON -DLGENG_HEADLESS=ON

      - name: Build
        run: |
          cmake --build build

      - name: Run tests
        run: |
          ctest --test-dir build/Tests --output-on-failure